service: geoip

provider:
  name: aws
  runtime: nodejs8.10
  profile: cheddarup
  memorySize: 256
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource:
      - Fn::Join:
        - ':'
        - - arn:aws:lambda
          - Ref: AWS::Region
          - Ref: AWS::AccountId
          - function:${self:service}-${opt:stage, self:provider.stage}-*

  stage: dev
  region: us-east-1

plugins:
  - serverless-plugin-warmup

functions:
  web:
    handler: handler.web
    warmup: true
    events:
      - http:
          path: location
          method: get
          cors: true
  logs:
    handler: handler.logs
    warmup: true
